DAY 3
Codeshows/100DaysOfCode pull request #153
Opened 2020-01-09 16:46 UTC by fantasy-08

**Progress update**

Day - 3 
Date - Jan 9
**Checklist**
- [ ] codechef problem - https://www.codechef.com/JAN20B/problems/ENGLISH (not yet successful)
- [ ] DOM manipulation in JS

2020-01-09 19:58 UTC, rishabhKalakoti requested changes

2020-01-09 19:58 UTC, rishabhKalakoti commented on esh_08/README.md
> +*Second year ECE, MNIT Jaipur*
Remove one of the readmes

2020-01-10 10:45 UTC, fantasy-08 reviewed
one README removed

2020-01-11 06:36 UTC, rishabhKalakoti approved these changes

2020-01-11 06:36 UTC, merged