Update readme.md
Codeshows/100DaysOfCode pull request #290
Opened 2020-02-03 15:28 UTC by mukulguptamg7

**Progress update**

Day - (write the day here: eg. day 1)

Date - (write the date on which the progress was made)

**Checklist**
- [ ] Self-review of the preview done.
- [ ] Updated Progress.
- [ ] Tweeted the Weekly/Daily Progress.

2020-02-07 06:12 UTC, rishabhKalakoti submitted a review, later dismissed

2020-02-07 06:13 UTC, rishabhKalakoti requested changes

2020-02-07 06:13 UTC, rishabhKalakoti commented on mukulguptamg7/readme.md
> +:: [my solution](https://www.codechef.com/viewsolution/29270628)
This came after day 29

2020-02-08 13:36 UTC, mukulguptamg7 reviewed
I have done the changes

2020-02-09 06:15 UTC, rishabhKalakoti approved these changes

2020-02-09 06:15 UTC, merged