Shashwat
Codeshows/100DaysOfCode pull request #74
Opened 2020-01-03 16:46 UTC by Shashwat-Gandhi

**Progress update**

Day - 2

Date - 2/1/2019

**Checklist**
- [x] Self-review of the preview done.
- [x] Updated Progress.
- [ ] Tweeted the Weekly/Daily Progress.

2020-01-03 18:07 UTC, ronakgadia requested changes

2020-01-03 18:07 UTC, ronakgadia commented on Shashwat-Gandhi/README.md
> +
Try to follow the Readme template

2020-01-04 06:06 UTC, Shashwat-Gandhi commented on Shashwat-Gandhi/README.md
> +
I changed the file, please take a look.

2020-01-04 09:20 UTC, rishabhKalakoti approved these changes

2020-01-04 09:20 UTC, merged